pipeline{

    stages{

        stage('Build'){

            steps {
                echo 'Building the application...'
                // Build the JAR file once
                bat 'mvn clean package -DskipTests'
            }

        }
    }
}