spring:
  application:
    name: returnJWT


  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}  # URL of your Admin Server
        instance:
          prefer-ip: true
          service-base-url: ${SERVICE_BASE_URL}


  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}


#  for case insensetivity in post body
  jackson:
    mapper:
      accept-case-insensitive-properties: true



CONNECT_SECRET: "CONNECT_SECRET"
WIDGET_ID: "WIDGET_ID"
JWT_EXP_DELTA_SECONDS: 500



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  security:
    enabled: false






server:
  port: 9000