spring:

  config:
    import: optional:file:.env-${spring.profiles.active}

  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=false;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}


  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:""}  # Default empty string if admin server is not available

cache:
  type: none


server:
  servlet:
    context-path: /api/v1


#logging:
##  config: classpath:logback-spring-purchase.xml
#  structured:
#    format:
#      console: ecs


#resilience4j.ratelimiter:
#  instances:
#    api-rate-limit:
#      limitForPeriod: 400
#      limitRefreshPeriod: 1s
#      timeoutDuration: 0
#      registerHealthIndicator: true
#      eventConsumerBufferSize: 100


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true