spring:

  config:
    import: optional:file:.env-${spring.profiles.active}

  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=false;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true


server:
  servlet:
    context-path: /purchase/api/v1


logging:
  config: classpath:logback-spring-purchase.xml