spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=false;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    #    hibernate:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

logging:
  config: classpath:logback-spring-PUR_dev.xml

server:
  port: 8090
  servlet:
    context-path: /purchase

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
