jdbcSettings:
#  url: "jdbc:h2:file:./db/blog;MODE=MySQL"
#  username: "user"
#  password: "pass"
#  driverClassName: "org.h2.Driver"
  url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=false;trustServerCertificate=true
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

packageName: "com.example.entity"